version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: na-auth-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpw
    ports:
      - 3307:3307
    env_file:
      - .env
    volumes:
      - /opt/mysql_data:/var/lib/mysql

volumes:
  mysql:
    name: nest-db
